name: DeathPenalty
version: '${project.version}'
description: Deduct HP, food, XP, level and money after player respawn
authors: [ MCUmbrella ]
website: https://github.com/MSUPlugins/DeathPenalty
main: vip.floatationdevice.msu.deathpenalty.DeathPenalty
api-version: 1.13
depend:
  - MSUCore
softdepend:
  - Vault
permissions:
  deathpenalty.bypass.hp:
    description: "Bypass HP deduction"
    default: op
  deathpenalty.bypass.food:
    description: "Bypass food deduction"
    default: op
  deathpenalty.bypass.xp:
    description: "Bypass XP and level deduction"
    default: op
  deathpenalty.bypass.money:
    description: "Bypass money deduction"
    default: op
